### ISSUE TITLE
Have problem when running install-sh, need some help please.

### ISSUE THREAD

**Issue by DennisLiu94** [botonchou/libdnn#14]
When I try to run install-sh, I have the following error:

g++ -Wall -o3  -I include/ -o example example.cpp -L lib/ -lmatrix -lpbar
/bin/sh: 1: ctags: not found
make: *** [ctags] 错误 127
./install-sh: 第 22 行: cd: tools/libcumatrix: 没有那个文件或目录

But I have the libcumatrix folder in the right position.

How can I fix this? You help will be really appreciated.

Thankyou.

PS: Ubuntu 14.04 64bit, g++4.8.2

**Comment by botonchou** [comment]
It means you don't have `ctags`, a package helps you to move cursor faster in vim.
NO need to have that to run the toolkit, but I still recommend you to install it:

```
sudo apt-get install exuberant-ctags
```

I'll remove the `ctags` dependencies in the next release.

**Comment by DennisLiu94** [comment]
Thank you very much.
