### ISSUE TITLE
error: namespace "thrust" has no member "max_element"

### ISSUE THREAD

**Issue by carlke** [botonchou/libdnn#24]
Hi, I got these error messages after executing ./install-sh:
src/dnn-utility.cu(153): error: namespace "thrust" has no member "max_element"
src/dnn-utility.cu(160): error: namespace "thrust" has no member "min_element"
src/dnn-utility.cu(166): error: namespace "thrust" has no member "max_element"
src/dnn-utility.cu(171): error: namespace "thrust" has no member "min_element"

Last command executed before error occurred was:
nvcc -arch=sm_21 -w  -Xcompiler -fPIC -I ./ -I include/ -I tools/utility//include/ -I tools/libcumatrix//include -I /usr/local/cuda/samples/common/inc/ -I /usr/local/cuda/include -o obj//dnn-utility.o -c src/dnn-utility.cu

Do you know why?

P.S. I'm using linux mint 17.1, gtx750ti, cuda toolkit 7, g++ 4.8.2

**Comment by shaform** [comment]
I got this error as well. I am using Ubuntu 14.04.2.
Cuda compilation tools, release 5.5, V5.5.0
g++ 4.8.2

**Comment by botonchou** [comment]
Hi @carlke and @shaform, where did you put CUDA? under `/usr/local/cuda/`?

**Comment by shaform** [comment]
Well, I found that I am actually using 7.0 as well.
Cuda compilation tools, release 7.0, V7.0.27
I install it with .deb (that might be the reason?), and I do find the relevant files in /usr/local/cuda/.

But I found that if I add the following line to `include/dnn-utility.h`, then the error disappears.

    #include <thrust/extrema.h>

However, the following error happens:

    include/dnn-utility.h(155): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

But if I add the following line to `Makefile`, I can compile it:

    NVCFLAGS=-Xcompiler -fPIC -std=c++11

So I am going to send a PR just for reference.

**Comment by carlke** [comment]
@botonchou Yes, I put it under /usr/local/cuda.
