### ISSUE TITLE
Using .zip files instead of git repositories for the dependencies in install-sh

### ISSUE THREAD

**Issue by beader** [botonchou/libdnn#5]
Hi, Chou

Thank you for bringing us this cool dnn tool. I have successfully installed it and run the examples with this tool.  The usage is as easy as libsvm and the experience is great !

However it takes me quite a while to install libdnn. In the `install-sh` I found 3 more dependencies are required while building libdnn. The first two are acquired by `git clone` and they need to download the whole git repository which may lager than 10 MB.

You know in some places the speed of connecting to github is an issue so replace the `git clone` procedure with `wget` may be better. 

```
wget https://codeload.github.com/botonchou/utility/zip/master -O tools/utility.zip
unzip tools/utility.zip -d tools/ && cd tools/utility-master && make o3 && cd -

wget https://codeload.github.com/botonchou/libcumatrix/zip/master -O tools/libcumatrix.zip
unzip tools/libcumatrix.zip -d tools/ && cd tools/libcumatrix-master && make o3 && cd -
```

**Comment by botonchou** [comment]
Add a options `--zip-only` in **./install.sh**. Like
```
./install.sh --zip-only
```
